datasets:
  mu_mimo:
    name: &dataset_name 'mu_mimo-env1_2x2-80mhz'
    type: 'MuMIMODataset'
    root: &root_dir !join ['./resource/datasets/mu-mimo/real/env1/', *dataset_name]
    splits:
      train:
        dataset_id: &train_split !join [*dataset_name, '/train']
        root_split_dir: &train_root_dir !join [*root_dir, '/train']
        params:
          h_mat_file_paths:
            - !join [*train_root_dir, '/rx1_2x1-h_mat.npy']
            - !join [*train_root_dir, '/rx2_2x1-h_mat.npy']
          v_mat_file_paths:
            - !join [*train_root_dir, '/rx1_2x1-v_mat.npy']
            - !join [*train_root_dir, '/rx2_2x1-v_mat.npy']
      val:
        dataset_id: &val_split !join [*dataset_name, '/val']
        root_split_dir: &val_root_dir !join [*root_dir, '/val']
        params:
          h_mat_file_paths:
            - !join [*val_root_dir, '/rx1_2x1-h_mat.npy']
            - !join [*val_root_dir, '/rx2_2x1-h_mat.npy']
          v_mat_file_paths:
            - !join [*val_root_dir, '/rx1_2x1-v_mat.npy']
            - !join [*val_root_dir, '/rx2_2x1-v_mat.npy']
      test:
        dataset_id: &test_split !join [*dataset_name, '/test']
        root_split_dir: &test_root_dir !join [*root_dir, '/test']
        params:
          h_mat_file_paths:
            - !join [*test_root_dir, '/rx1_2x1-h_mat.npy']
            - !join [*test_root_dir, '/rx2_2x1-h_mat.npy']
          v_mat_file_paths:
            - !join [*test_root_dir, '/rx1_2x1-v_mat.npy']
            - !join [*test_root_dir, '/rx2_2x1-v_mat.npy']

models:
  model:
    name: &model_name 'HtoV'
    params:
      encoder_node_counts: [968, 121]
      decoder_node_counts: [121, 968]
    experiment: &experiment !join ['mu_mimo-env2_2x2-80mhz-', *model_name, '_968-121-968-epoch40_sim-pretrained_adam']
    start_ckpt: './resource/ckpt/mu_mimo-a1_2x2-80mhz/norm_mse/mu_mimo-a1_2x2-80mhz-HtoV_968-121-968-epoch40.pt'
    ckpt: !join ['./resource/ckpt/mu_mimo-env2_2x2-80mhz/norm_mse/', *experiment, '.pt']

train:
  matlab_eval_config: &matlab_eval_config !join [*root_dir, '/config.mat']
  uses_sim_data: False
  log_freq: 100
  num_epochs: 40
  train_data_loader:
    dataset_id: *train_split
    random_sample: True
    batch_size: 4
    num_workers: 0
    requires_supp: False
    cache_output:
  val_data_loader:
    dataset_id: *val_split
    random_sample: False
    batch_size: 2000
    num_workers: 0
    requires_supp: False
  model:
    adaptations:
    sequential: []
    wrapper: 'DistributedDataParallel'
    requires_grad: True
    frozen_modules: []
  apex:
    requires: False
    opt_level: '01'
  optimizer:
    type: 'Adam'
    params:
      lr: 0.001
  scheduler:
    type: 'MultiStepLR'
    params:
      milestones: [20, 30]
      gamma: 0.1
  criterion:
    type: 'GeneralizedCustomLoss'
    org_term:
      criterion:
        type: 'NormalizedReconstructionLoss'
        params: {}
      factor: 1.0
    sub_terms:

test:
  matlab_eval_config: *matlab_eval_config
  uses_sim_data: False
  test_data_loader:
    dataset_id: *test_split
    random_sample: False
    batch_size: 2000
    num_workers: 0
